name: Build Vite and publish docs folder

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build (outDir=docs)
        run: npm run build

      - name: Add .nojekyll
        run: |
          touch docs/.nojekyll

      - name: Commit built docs (optional)
        if: ${{ github.event_name == 'push' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/.nojekyll
          git commit -m "chore: ensure .nojekyll in docs" || echo "No changes"

  # Not deploying via Actions; configure Pages to serve from main/docs in settings
